---
title: "P8105 Final Project Proposal"
output: github_document
---

### Group members

Trisha Dwivedi (trishad1), Pooja Mukund (pm3148), Ragyie Rawal (rr3423), Safiya Sirota (sns2189), Eric Wang (ew2717)

### Tentative project title

Healthcare expenditure patterns in the U.S. compared to other countries

### Motivation

We hope to understand and present healthcare funding patterns in various countries. We want to show who is bearing the brunt of the costs and how spending distributions differ throughout the world. Several countries rely on the WHO for healthcare, treatment, and research funding, so recognizing underfunded areas is paramount to ensure care for everyone globally. We also hope to compare spending in specific countries across different areas, including: primary health care, infectious diseases, noncommunicable diseases, preventive, and curative care. 

### Intended Final Products

We will create a website with an interactive dashboard in order to draw in a broad audience and make large amounts of WHO data accessible and informative. 

### Data Source

World Health Organization's Global Health Expenditure Database: https://apps.who.int/nha/database/Home/Index/en

### Planned analyses, visualizations, and coding challenges

*Questions for analysis*: How does spending compare per capita between countries with high and low socioeconomic status? Are countries putting enough resources into their most prevalent diseases? How much do different countries spend on curative vs. preventive care? How much do out of pocket costs, government funding, and private insurance companies contribute?

*Visualizations*: A dashboard comparing amounts of funding received for different categories for each country. An interactive world map of health expenditure information. A stacked bar plot of expenditures. A line plot showing how health expenditure has changed over time for multiple countries.

*Coding challenges*: Dealing with missing data values. Understanding economics terminology and pulling the correct variables for analysis. Using pivot_longer to properly tidy the dataset (the current columns are years).

### Planned Timeline

* November 19: Have project review meeting
* November 23: Complete data tidying 
* November 30: Complete planned analyses, visualizations
* December 11: Complete discussion of results, finalize report, create deliverables
