name: "GHED Project"
output_dir: "."
navbar:
  title: "GHED Project"
  left:
    - text: "About Us"
      href: about.html
  right:
    - icon: fa-envelope fa-lg
      href: mailto:<wang.eric@columbia.com>
    - icon: fa-github fa-lg
      href: http://github.com/ericwanghu/
output:
  html_document:
    theme: simplex